import Constants.NAME
import Constants.TITLE
import Constants.VERSION
import config.BuildConfig
import kotlinx.datetime.*

/**
 * Holds constants of the application.
 *
 * @property NAME The name of the application.
 * @property VERSION The version of the application.
 * @property TITLE The title of the application.
 */
data object Constants {
    /**
     * The name of the application.
     */
    const val NAME = BuildConfig.NAME

    /**
     * The version of the application.
     */
    const val VERSION = BuildConfig.VERSION

    /**
     * The organization behind the application.
     */
    const val ORG = BuildConfig.ORG_SHORT

    /**
     * The developer of the application.
     */
    const val DEV = BuildConfig.DEV

    /**
     * The title of the application.
     */
    const val TITLE = "$NAME v$VERSION"

    const val COPYRIGHT = "Copyright @ ${BuildConfig.YEAR} ${BuildConfig.ORG}"
    const val DEV_SIGN = "Developed by ${BuildConfig.DEV}"



    fun sign(): String = "generated by $NAME v$VERSION at ${Clock.System.now().toLocalDateTime(TimeZone.currentSystemDefault()).format(LocalDateTime.Formats.ISO)}"
}